#!/bin/sh

# Script to start firmware

#DIR=~/Repos/tedi-uavcommandforward/1_Code/Firmware ID="$1"

ID="$@" dbus-launch gnome-terminal -- bash  -c '
	UAV_ID="$ID" su - pi -c "
		cd ~/Repos/tedi-uavcommandforward/1_Code/Firmware;
		DONT_RUN=1 make px4_sitl_default gazebo; 
		source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default;	
		export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd):$(pwd)/Tools/sitl_gazebo;
		roslaunch px4 multi_uav${UAV_ID}_mavros_sitl.launch gui:=false;
		exec bash
	";
	exec bash
' 

echo  "End of Script"

